apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school

resources:
- ../../base

images:
- name: school-academics
  newName: ghcr.io/ediong-dev/school-academics
  newTag: 341434be57f2321a5b586701cf3cb15997e54c8a
- name: school-auth
  newName: ghcr.io/ediong-dev/school-auth
  newTag: 341434be57f2321a5b586701cf3cb15997e54c8a
- name: school-dashboard
  newName: ghcr.io/ediong-dev/school-dashboard
  newTag: 341434be57f2321a5b586701cf3cb15997e54c8a
- name: school-gateway
  newName: ghcr.io/ediong-dev/school-gateway
  newTag: 341434be57f2321a5b586701cf3cb15997e54c8a
