apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school

resources:
- ../../base

images:
- name: school-academics
  newName: ghcr.io/ediong-dev/school-academics
  newTag: a9b3875fc59ea400824636314f125db3f4d6e00d
- name: school-auth
  newName: ghcr.io/ediong-dev/school-auth
  newTag: a9b3875fc59ea400824636314f125db3f4d6e00d
- name: school-dashboard
  newName: ghcr.io/ediong-dev/school-dashboard
  newTag: a9b3875fc59ea400824636314f125db3f4d6e00d
- name: school-gateway
  newName: ghcr.io/ediong-dev/school-gateway
  newTag: a9b3875fc59ea400824636314f125db3f4d6e00d
