apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school

resources:
- ../../base

images:
- name: school-academics
  newName: ghcr.io/ediong-dev/school-academics
  newTag: 46b2e27bd7496b60f380bfcb02e8a7099a5837b9
- name: school-auth
  newName: ghcr.io/ediong-dev/school-auth
  newTag: 46b2e27bd7496b60f380bfcb02e8a7099a5837b9
- name: school-dashboard
  newName: ghcr.io/ediong-dev/school-dashboard
  newTag: 46b2e27bd7496b60f380bfcb02e8a7099a5837b9
- name: school-gateway
  newName: ghcr.io/ediong-dev/school-gateway
  newTag: 46b2e27bd7496b60f380bfcb02e8a7099a5837b9
