apiVersion: batch/v1
kind: Job
metadata:
  name: locust-10-users
  namespace: school
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: locust
          image: locustio/locust:2.32.0
          args:
            - "-f"
            - "/scripts/locustfile.py"
            - "--headless"
            - "--host"
            - "http://gateway-stable:3000"
            - "-u"
            - "10"
            - "-r"
            - "2"
            - "-t"
            - "2m"
            - "--only-summary"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: locust-script