apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gateway-error-rate
  namespace: school
spec:
  metrics:
    - name: error-rate
      interval: 15s
      failureLimit: 3
      successCondition: result[0] < 0.05
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            (
              sum(rate(http_requests_total{service=~"gateway.*", status=~"5.."}[5m]))
              /
              sum(rate(http_requests_total{service=~"gateway.*"}[5m]))
            )
            or
            (0 * sum(rate(http_requests_total{service=~"gateway.*"}[5m])))
