apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gateway-error-rate
  namespace: school
spec:
  metrics:
    - name: error-rate
      interval: 15s
      failureLimit: 3
      successCondition: result[0] < 0.05
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(
              school:http_error_ratio:rate5m{
                service="gateway"
              }
            )