---
apiVersion: v1
kind: ConfigMap
metadata:
  name: school-config
  namespace: school
data:
  AUTH_URL: "http://auth:3001"
  ACADEMICS_URL: "http://academics-WRONG:3002"
  DASHBOARD_URL: "http://dashboard:3003"