---
apiVersion: v1
kind: Service
metadata:
  name: gateway-stable
  namespace: school
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-canary
  namespace: school
  labels:
    app: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gateway
  namespace: school
  labels:
    app: gateway
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: gateway
          image: ghcr.io/ediong-dev/school-gateway:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: school-config-fggmbfc622
          env:
            - name: GATEWAY_FAILURE_RATE
              value: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
  strategy:
    canary:
      stableService: gateway-stable
      canaryService: gateway-canary
      analysis:
        templates:
          - templateName: gateway-error-rate
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100