apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school

resources:
  - auth-secret.yaml
  - config.yaml
  - auth.yaml
  - academics.yaml
  - dashboard.yaml
  - gateway.yaml