apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school

resources:
  - auth-secret.yaml
  - auth.yaml
  - academics.yaml
  - dashboard.yaml
  - gateway-rollout.yaml
  - analysis-template.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - postgres-init.yaml
  - servicemonitor-auth.yaml
  - servicemonitor-academics.yaml
  - servicemonitor-dashboard.yaml
  - servicemonitor-gateway.yaml
  - prometheusrules-sli.yaml
  - prometheusrules-alerts.yaml
  - alertmanagerconfig.yaml

configMapGenerator:
  - name: school-config
    envs:
      - config.env
    options:
      disableNameSuffixHash: false
