apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: academics
  namespace: school
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: academics
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
